runs:
  using: composite

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Setup workspace
      if: ${{ env.WORKSPACE }}
      shell: bash
      run: pnpm run --if-present ${{ env.WORKSPACE }}:ci-setup
