packages:
  - "external/*"
  - "internal/*"
  - "modules/*"
  - "examples/*"

catalog:
  "@types/node": ^22.13.10
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@vitejs/plugin-react": ^4.3.4
  "@vitest/coverage-v8": ^2.1.2
  classnames: ^2.5.1
  depcheck: ^1.4.7
  eslint: ^9.19.0
  prettier: ^3.4.2
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.2
  vite: ^6.2.1
  vitest: ^2.1.2
