packages:
  - "internal/*"
  - "modules/*"
  - "examples/*"

catalog:
  "@types/node": ^22.13.10
  "@vitest/coverage-v8": ^2.1.2
  depcheck: ^1.4.7
  eslint: ^9.19.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  vite: ^6.2.1
  vitest: ^2.1.2
