inputs:
  github-token:
    description: "The token for pushing tags and version changes to github.."
    required: true
  npm-token:
    description: "The token for publishing the package to npm."
    required: true
  segment:
    description: "The version segment to increment: major, minor, patch, or prerelease."
    required: true
  preId:
    description: 'Appended to the prerelease segment. (default: "")'

runs:
  using: composite

  steps:
    - name: Determine Tag
      id: tag
      shell: bash
      run: |
        if [[ ${{ inputs.segment }} == pre* ]]; then
          echo "tag=next" >> $GITHUB_OUTPUT
        else
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi

    - name: Increment Version
      working-directory: ${{ env.DIRECTORY }}
      shell: bash
      run: |
        git config --local user.name "Workflow: ${{ env.WORKSPACE }}"
        git config --local user.email "${{ env.WORKSPACE }}@workflow"

        if [[ ${{ inputs.segment }} == pre* ]]; then
          if [[ -n "${{ inputs.preId }}" ]]; then
            PREID_CMD="--preid ${{ inputs.preId }}"
          fi
        fi

        pnpm version ${{ inputs.segment }} $PREID_CMD

        VERSION="$(cat package.json | jq -r '.version')"
        git commit --all --message "Publish ${{ env.WORKSPACE }} v$VERSION"
        git tag "${{ env.WORKSPACE }}/v$VERSION"

    - name: Push Tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ github.ref }}
        tags: true

    - name: Publish to NPM Registry
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ inputs.npm-token }}
        package: ${{ env.DIRECTORY }}
        access: public
        tag: ${{ steps.tag.outputs.tag }}
