name: Scripts

on:
  workflow_dispatch:
  push:
    # paths:
    #   - "common/scripts/**"

env:
  WORKSPACE: "scripts"
  DIRECTORY: common/scripts

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify
        uses: ./.github/actions/verify

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: verify
    if: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        uses: ./.github/actions/test
