name: Tooling

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/internal-tooling.yml
      - internal/tooling/**

env:
  WORKSPACE: "@overlaysymphony/tooling"
  DIRECTORY: internal/tooling

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify
        uses: ./.github/actions/verify
