name: "Module: Twitch"

on:
  workflow_dispatch:
  push:
    # paths:
    #   - "packages/twitch/**"

env:
  WORKSPACE: "@overlaysymphony/twitch"
  DIRECTORY: packages/twitch

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify
        uses: ./.github/actions/verify

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: verify
    if: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        uses: ./.github/actions/test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [verify, test]
    if: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build
