name: "Module: Overlays"

on:
  push:
    # paths:
    #   - modules/overlays/**
  workflow_dispatch:
    inputs:
      segment:
        description: "The version segment to increment: major, minor, patch, or prerelease."
        required: true
      preId:
        description: 'Appended to the prerelease segment. (default: "")'

env:
  WORKSPACE: "@overlaysymphony/overlays"
  DIRECTORY: modules/overlays

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify
        uses: ./.github/actions/verify

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        uses: ./.github/actions/test
        if: false

  build:
    name: ${{ github.event_name == 'workflow_dispatch' && 'Build and Publish' || 'Build'  }}
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && 'npm' || null  }}
    needs: [verify, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      # - name: Build
      #   uses: ./.github/actions/build

      - name: Publish
        uses: ./.github/actions/publish
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          segment: ${{ github.event.inputs.segment }}
          preId: ${{ github.event.inputs.preId }}
