name: Public

on:
  workflow_dispatch:
  push:
    # paths:
    #   - "internal/public/**"

env:
  WORKSPACE: "public"
  DIRECTORY: internal/public

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify
        uses: ./.github/actions/verify

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    needs: verify

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build
        env:
          VITE_TWITCH_CLIENT_ID: ${{ vars.TWITCH_CLIENT_ID }}
        with:
          args: --base=/${{ github.event.repository.name }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./internal/public/dist

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build

    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
      contents: write
      packages: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
